### PR TITLE
update debian packaging

### PR DESCRIPTION
**Pull request by barak**

### CODE REVIEW

**Review by rastersoft — CHANGES_REQUESTED** [review]
I uploaded some changes in these files made automagically by autovala. If you help me, I can integrate these changes into autovala to ensure that it generates the files right.

**Comment by barak** [comment]
Sure, how can I help? The debian/* scripts generated by autovala seem a bit dated, I was mainly updating them. I can explain some of the changes I made:

* debian/compat and a versioned build dependency on debhelper (>= 11) to be up to date.
* remove build-essential as a build dependency as it is implicit. Remove some others which are in build-essential anyway
* let debhelper figure out the runtime library dependencies
* simplify debian/rules using default actions including automatic cmake support

I've pushed a few more commits, mainly to address issues lintian complained about.

* need a debian/copyright file
* disapproval of /usr/bin/*.sh
* register terminus as n x-terminal-emulator
* typo in changelog
* deprecated construct in .desktop files
* maintainer scripts should not ignore errors
* use (unnecessary I think) hardening compilation options
* allow debhelper to add material to install-time scripts if it wants to
* specify source format
* allow default trigger mechanism to handle schemas

I'd be happy to go into more detail if that helps update autovala. Clearly not quite all of this can be automated.

**Comment by rastersoft** [comment]
A question: in the line

    Depends: ${shlibs:Depends}, ${misc:Depends}

can I add more dependencies after that? Let's say that a program depends on the binary XXXX. Can I add it after that?

**Comment by rastersoft** [comment]
Why did you use version 11 inside compat file, when I read that the current version is 10? Also, why the "plus" sign before the number?

https://www.debian.org/doc/manuals/maint-guide/dother.html#compat

**Comment by rastersoft** [comment]
Devhelper (>=11)... That number must be the same than the one in the compat file?

**Comment by barak** [comment]
Well, the version of debhelper must be >= the number in debian/compat. I suppose if you want to use compatibility level 8 but some bug was fixed later you could require a version greater than the compatibility level, but I've never had to. Anyway, the current level is 11, I guess this hasn't percolated out to all the documentation. But I don't think the package really needs anything above 9 or 10. The newer automatic goodies are always nice though, like how it finds the upstream changelog file without being told.

Yes, you can add more dependencies after ${misc:Depends} etc. Debhelper will adjust commas appropriately etc.

Um, what plus sign?

**Comment by rastersoft** [comment]
Sorry for the delay, I've been quite busy with my job.

I've been adding some of the changes into both the terminus repository and autovala, but now I have some doubts, specifically about debhelper... I presume that it just replaces all the code inside the RULES file, isn't it?

(about the plus sign, I suspect it is just the plus from the diff file, so don't bother. Sorry).

**Comment by barak** [comment]
Oops, I didn't actually do anything to close this, except merge your branch into mine...

Yes, debhelper basically pulls smarts (policy, knowledge of how to build the package) out of debian/rules and into generic support scripts not unique to any package. There has been a systematic attempt to automate as much as possible, so automatically triggering necessary installation hooks based on filenames (e.g., running ldconfig automatically as necessary, compiling gconf files, etc). This has worked out pretty well in reducing the complexity of the individual per-package packaging scripts, and making the entire system more robust to policy changes by simply rebuilding packages automatically.

**Pull request closed without merging**
